services:
  api-server:
    build:
      context: ./backend/
      args:
        - "db_type=sqlite"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./data/:/data/

  reverse_proxy:
    build: ./reverse_proxy/
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./data/public/:/data/
    depends_on:
      - api-server
    ports:
      - "8000:80"
