# For my own dev convenience, change it to
# ./.env while deploying
x-env: &env
  env_file: [ "../../.env" ]

services:
  init:
    build:
      context: ./backend/
      dockerfile: Dockerfile.init
      args:
        - "db_type=sqlite"
    <<: *env
    restart: on-failure
    volumes:
      - ./data/:/data/

  api-server:
    build:
      context: ./backend/
      args:
        - "db_type=sqlite"
    <<: *env
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    depends_on:
      init:
        condition: service_completed_successfully

  reverse_proxy:
    build: ./reverse_proxy/
    <<: *env
    restart: unless-stopped
    volumes:
      - ./data/public/:/data/public/
    depends_on:
      - api-server
    ports:
      - "8000:8000"
