FROM golang:1.27.0-alpine3.23@sha256:3747dcba41c8b0db3211fda4db61638b980e17ac5bb3c94460a975a9cfe19395 AS builder

WORKDIR /opt/backend/

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/root/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go mod download

COPY internal/frontend/ internal/frontend/
RUN  --mount=type=cache,target=/root/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go tool templ generate

ARG db_type=sqlite
COPY . .
RUN  --mount=type=cache,target=/root/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go build \
  -ldflags="-s -w" \
  -tags="${db_type},init" \
  -o ./bin/init \
  ./cmd/init/

FROM scratch

COPY --from=builder /opt/backend/bin/init .

ENTRYPOINT [ "./init" ]
